#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
A console which connects to a daemon of Clownfish
"""
from pyclownfish import clownfish_console

if __name__ == "__main__":
    clownfish_console.main()
