#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Start a server of Clownfish
"""
from pyclownfish import clownfish_server

if __name__ == "__main__":
    clownfish_server.main()
