#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Generate clownfish_test.conf
"""
from pyclownfish import gen_clownfish_test

if __name__ == "__main__":
    gen_clownfish_test.main()
