#!/usr/bin/python -u
# Copyright (c) 2017 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Build Clownfish
"""
from pybuild import lbuild

if __name__ == "__main__":
    lbuild.main()
