#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Start the console to the scheduler
"""
from pyltest import ltest_console

if __name__ == "__main__":
    ltest_console.main()
