#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Start the test process
"""
from pyltest import ltest_launch

if __name__ == "__main__":
    ltest_launch.main()
