#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Start the scheduler
"""
from pyltest import ltest_scheduler

if __name__ == "__main__":
    ltest_scheduler.main()
