#!/usr/bin/python -u
# Copyright (c) 2018 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Install virtual machines
"""
from pylustre import lvirt

if __name__ == "__main__":
    lvirt.main()
