#!/usr/bin/python -u
# Copyright (c) 2019 DataDirect Networks, Inc.
# All Rights Reserved.
# Author: lixi@ddn.com
"""
Check the import of pyltest source code
"""
from pybuild import pyltest_import_check

if __name__ == "__main__":
    pyltest_import_check.main()
