"""
Constatnts used in Clownfish
"""
ETC_DIR_PATH = "/etc/"
VAR_LOG_PATH = "/var/log"

CLOWNFISH_BUILD_CONFIG_FNAME = "clownfish_build.conf"
CLOWNFISH_BUILD_CONFIG = ETC_DIR_PATH + CLOWNFISH_BUILD_CONFIG_FNAME
CLOWNFISH_BUILD_LOG_DIR_BASENAME = "clownfish_build_log"

CLOWNFISH_INSTALL_CONFIG_FNAME = "clownfish_install.conf"
CLOWNFISH_INSTALL_CONFIG = ETC_DIR_PATH + CLOWNFISH_INSTALL_CONFIG_FNAME
CLOWNFISH_INSTALL_LOG_DIR_BASENAME = "clownfish_install"
CLOWNFISH_INSTALL_LOG_DIR = VAR_LOG_PATH + "/" + CLOWNFISH_INSTALL_LOG_DIR_BASENAME

CLOWNFISH_CONFIG_FNAME = "clownfish.conf"
CLOWNFISH_CONFIG = "/etc/" + CLOWNFISH_CONFIG_FNAME
CLOWNFISH_LOG_DIR = "/var/log/clownfish"

CLOWNFISH_TEST_LOG_DIR_BASENAME = "clownfish_test"
CLOWNFISH_TEST_LOG_DIR = VAR_LOG_PATH + "/" + CLOWNFISH_TEST_LOG_DIR_BASENAME
CLOWNFISH_TEST_CONFIG_FNAME = "clownfish_test.conf"
CLOWNFISH_TEST_CONFIG = "/etc/" + CLOWNFISH_TEST_CONFIG_FNAME

CLOWNFISH_DEFAULT_SERVER_PORT = 3002
